#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v7
# autospec commit: f56f1fa
#
Name     : R-WikipediR
Version  : 1.7.1
Release  : 43
URL      : https://cran.r-project.org/src/contrib/WikipediR_1.7.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/WikipediR_1.7.1.tar.gz
Summary  : A MediaWiki API Wrapper
Group    : Development/Tools
License  : MIT
Requires: R-httr
Requires: R-jsonlite
Requires: R-magrittr
BuildRequires : R-httr
BuildRequires : R-jsonlite
BuildRequires : R-magrittr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Wikimedia 'production' wikis, such as Wikipedia. It can be used to retrieve
    page text, information about users or the history of pages, and elements of
    the category tree.

%prep
%setup -q -n WikipediR
pushd ..
cp -a WikipediR buildavx2
popd
pushd ..
cp -a WikipediR buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1712456578

%install
export SOURCE_DATE_EPOCH=1712456578
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/WikipediR/DESCRIPTION
/usr/lib64/R/library/WikipediR/INDEX
/usr/lib64/R/library/WikipediR/LICENSE
/usr/lib64/R/library/WikipediR/Meta/Rd.rds
/usr/lib64/R/library/WikipediR/Meta/features.rds
/usr/lib64/R/library/WikipediR/Meta/hsearch.rds
/usr/lib64/R/library/WikipediR/Meta/links.rds
/usr/lib64/R/library/WikipediR/Meta/nsInfo.rds
/usr/lib64/R/library/WikipediR/Meta/package.rds
/usr/lib64/R/library/WikipediR/Meta/vignette.rds
/usr/lib64/R/library/WikipediR/NAMESPACE
/usr/lib64/R/library/WikipediR/NEWS
/usr/lib64/R/library/WikipediR/R/WikipediR
/usr/lib64/R/library/WikipediR/R/WikipediR.rdb
/usr/lib64/R/library/WikipediR/R/WikipediR.rdx
/usr/lib64/R/library/WikipediR/doc/WikipediR.Rmd
/usr/lib64/R/library/WikipediR/doc/WikipediR.html
/usr/lib64/R/library/WikipediR/doc/index.html
/usr/lib64/R/library/WikipediR/help/AnIndex
/usr/lib64/R/library/WikipediR/help/WikipediR.rdb
/usr/lib64/R/library/WikipediR/help/WikipediR.rdx
/usr/lib64/R/library/WikipediR/help/aliases.rds
/usr/lib64/R/library/WikipediR/help/paths.rds
/usr/lib64/R/library/WikipediR/html/00Index.html
/usr/lib64/R/library/WikipediR/html/R.css
/usr/lib64/R/library/WikipediR/tests/testthat.R
/usr/lib64/R/library/WikipediR/tests/testthat/test_category_retrieval.R
/usr/lib64/R/library/WikipediR/tests/testthat/test_content_retrieval.R
/usr/lib64/R/library/WikipediR/tests/testthat/test_metadata_retrieval.R
/usr/lib64/R/library/WikipediR/tests/testthat/test_recent_changes.R
